---
title: "Lists"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lists}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
#| label: packages
#| message: false
#| warning: false
library(ttdviewer)
library(listviewerlite)
library(lobstr)
library(dplyr)
library(tidyr)
```


## List objects

Below we'll define an `example_list`:

```{r}
#| label: example_list
#| code-fold: true
#| code-summary: 'show/hide example_list'
example_list <- list(
  list(
    id = "A",
    level = 1,
    vals = c(2.1, 3.3)
  ),
  list(
    id = "B",
    level = 1,
    vals = c(1.2, 2.5, 3.1),
    children =
      list(
        list(
          id = "B1",
          level = 2,
          vals = 2.5
        ),
        list(
          id = "B2",
          level = 2,
          vals = 0.8,
          children =
            list(
              list(
                id = "b21",
                level = 3,
                vals = 4.0
              )
            )
        )
      )
  ),
  list(
    id = "C",
    level = 1,
    vals = c(4.2, 8.8),
    children =
      list(
        list(
          id = "C1",
          level = 2,
          vals = c(9.1, 4.6)
        ),
        list(
          id = "C2",
          level = 2,
          vals = c(1.1, 3.4)
        )
      )
  )
)
```

### custom_tree()

```{r}
#| label: custom_tree
custom_tree <- function(x = as.list(), depth = 10L, length = 50L) {
  lobstr::tree(x,
    max_depth = depth,
    max_length = length,
    show_environments = FALSE,
    show_attributes = FALSE,
    hide_scalar_types = TRUE,
    class_printer = crayon::blue,
    remove_newlines = TRUE,
    val_printer = crayon::green
  )
}
```

```{r}
custom_tree(x = example_list)
```

### listviewerlite::listview()

```{r}
listviewerlite::listview(x = example_list)
```

## TidyTuesday data lists 

### Two datasets

```{r}
#| label: ttd2
ttd2 <- load_tt_data("Space Launches")
```

```{r}
custom_tree(x = ttd2)
```

```{r}
listviewerlite::listview(ttd2)
```

### Three datasets

```{r}
#| label: ttd3
ttd3 <- load_tt_data("Moore’s Law")
```

```{r}
custom_tree(x = ttd3)
```

```{r}
listviewerlite::listview(ttd3)
```
